Name:           ros-indigo-turtlebot-teleop
Version:        2.3.3
Release:        0%{?dist}
Summary:        ROS turtlebot_teleop package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/turtlebot_teleop
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-joy
Requires:       ros-indigo-kobuki-safety-controller
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-turtlebot-bringup
Requires:       ros-indigo-yocs-velocity-smoother
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-joy
BuildRequires:  ros-indigo-roscpp

%description
Provides teleoperation using joysticks or keyboard.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Jan 05 2015 Melonee Wise <mwise@willowgarage.com> - 2.3.3-0
- Autogenerated by Bloom

* Tue Dec 30 2014 Melonee Wise <mwise@willowgarage.com> - 2.3.2-0
- Autogenerated by Bloom

